version: 2.1
orbs:
  node: circleci/node@6.1.0
jobs:
  test-backend:
    docker:
      - image: cimg/node:lts
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: server
      - run:
          name: Run Backend Tests
          command: |
            cd server
            npm run test

  test-frontend:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: client
      - run:
          name: Run Frontend Tests
          command: |
            cd client
            npm run test

  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm run install-all
      - run:
          name: Build Client
          command: npm run build --prefix client
      - run:
          name: Build Server
          command: npm run build --prefix server
      - run:
          name: Compile Migrations
          command: |
            cd server
            npx tsc migrations/*.ts --outDir dist/migrations
      - persist_to_workspace:
          root: .
          paths:
            - client/build
            - server/dist
            - server/package.json
            - server/package-lock.json

  deploy:
    machine: 
      image: ubuntu-2204:current
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - add_ssh_keys:
          fingerprints:
            - "SHA256:6+qHFQDbqCYFzFzHfY7fpBaly2rEB83DUxswOGj6dkI"
      - run:
          name: Copy compiled migrations to server
          command: |
            if [ -d "/home/circleci/project/server/dist/migrations" ] && [ "$(ls -A /home/circleci/project/server/dist/migrations)" ]; then
              scp -r /home/circleci/project/server/dist/migrations/* $SERVER_USER@$SERVER_IP:$SERVER_DIR/server/migrations
            else
              echo "No compiled migrations to copy"
            fi
      - run:
          name: Run database migrations
          command: |
            ssh -v $SERVER_USER@$SERVER_IP "cd $SERVER_DIR/server && NODE_ENV=production npm run migrate || echo 'No migrations to run'"
      - run:
          name: Deploy to Server
          command: |
            scp -r /home/circleci/project/client/build/* $SERVER_USER@$SERVER_IP:$SERVER_DIR/client
            scp -r /home/circleci/project/server/dist/* /home/circleci/project/server/package*.json $SERVER_USER@$SERVER_IP:$SERVER_DIR/server
            ssh $SERVER_USER@$SERVER_IP "cd $SERVER_DIR/server && npm install --production && pm2 restart $SERVER_DIR/server/ecosystem.config.js && sudo systemctl restart nginx"

workflows:
  test-build-and-deploy:
    jobs:
      - test-backend:
          filters:
            branches:
              only: master
      - test-frontend:
          filters:
            branches:
              only: master
      - build:
          requires:
            - test-backend
            - test-frontend
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master